version: '3.4'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./volumes/pgdata:/var/lib/postgresql/data
    ports:
      - ${DATABASE_PORT}:5432
  influxdb:
    container_name: rnkm63-influxdb
    image: quay.io/influxdb/influxdb:2.0.0-rc
    environment:
      TZ: Asia/Bangkok
    ports:
      - 8086:8086
    volumes:
      - ./volumes/influxdb:/var/lib/influxdb2
    command: bash -c 'influxd run --bolt-path /var/lib/influxdb2/influxd.bolt --engine-path /var/lib/influxdb2/engine --store bolt'
  chulassomock:
    image: pay2630/chulassomock
    restart: always
    ports:
      - 8080:8080
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_LISTEN_PORT: ${PGADMIN_PORT}
    ports:
      - ${PGADMIN_PORT}:${PGADMIN_PORT}
    volumes:
      - ./pgadmin/servers.json:/pgadmin4/servers.json
